name: app_flutter
description: Aplicación móvil Clarita
publish_to: "none"

environment:
  sdk: ">=3.10.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  sqflite: ^2.3.3
  path: ^1.9.0
  path_provider: ^2.1.4
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
